---
# playbook for deploying colorforcode.com
- hosts: colorforcode
  sudo: yes

  vars:
    app_name: ColorForCode
    repo_url: https://github.com/jackson-/colorforcode.git
    repo_remote: origin
    repo_version: master
    webapps_dir: ~/

  tasks:
      - name: ping server
        ping:

      - name: git pull project
        git: repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version=master
      
      - name: Running NPM install
        npm: path={{webapps_dir}}/{{app_name}}

      - name: run npm build script (front-end)
        shell: npm run build
        args:
          chdir: ~/ColorForCode
      - name: restart nginx
        service: name=nginx state=restarted