/* ----------- JOBS ------------ */
export const RECEIVE_JOBS = 'RECEIVE_JOBS'
export const RECEIVE_JOB = 'RECEIVE_JOB'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_USER_JOBS = 'RECEIVE_USER_JOBS'
export const RECEIVE_APPLIED_JOBS = 'RECEIVE_APPLIED_JOBS'

/* ----------- LOADING ------------ */
export const REQUEST_ALL_JOBS = 'REQUEST_ALL_JOBS'
export const REQUEST_APPLIED_JOBS = 'REQUEST_APPLIED_JOBS'
export const REQUEST_FILTERED_JOBS = 'REQUEST_FILTERED_JOBS'
export const REQUEST_FILTERED_USERS = 'REQUEST_FILTERED_USERS'
export const APPLY_TO_JOB = 'APPLY_TO_JOB'
export const APPLIED_TO_JOB = 'APPLIED_TO_JOB'
export const REQUEST_USER = 'REQUEST_USER'
export const REQUEST_USER_JOBS = 'REQUEST_USER_JOBS'
export const REQUEST_ALL_SKILLS = 'REQUEST_ALL_SKILLS'
export const RECEIVE_ALL_SKILLS = 'RECEIVE_ALL_SKILLS'
export const REQUEST_JOB = 'REQUEST_JOB'
export const CREATE_JOB = 'CREATE_JOB'
export const UPDATE_JOB = 'UPDATE_JOB'
export const DELETE_JOB = 'DELETE_JOB'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const BEGIN_UPLOADING = 'BEGIN_UPLOADING'
export const DONE_UPLOADING = 'DONE_UPLOADING'

/* ----------- USERS ------------ */
export const AUTHENTICATED = 'AUTHENTICATED'
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS'

/* ------------ ROUTER STATE ------------ */
export const RECEIVE_ROUTER_STATE = 'RECEIVE_ROUTER_STATE'
