# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='role',
            field=models.CharField(default=b'job_seeker', max_length=40),
        ),
    ]
